<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="0" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="35" started-at="2017-08-04T07:34:04Z" finished-at="2017-08-04T07:34:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="35" started-at="2017-08-04T07:34:04Z" finished-at="2017-08-04T07:34:04Z">
      <class name="whayer.cloud.framework.db.test.HibernateDaoTest">
        <test-method status="FAIL" signature="testGetDao()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testGetDao" is-config="true" duration-ms="558" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <exception class="org.springframework.beans.factory.CannotLoadBeanClassException">
            <message>
              <![CDATA[Cannot find class [whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory] for bean with name 'myBatisSessionFactory' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory] for bean with name 'myBatisSessionFactory' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1385)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:641)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1007)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:741)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at whayer.cloud.framework.db.test.HibernateDaoTest.testGetDao(HibernateDaoTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:401)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1432)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1377)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- org.springframework.beans.factory.CannotLoadBeanClassException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDao -->
        <test-method status="SKIP" signature="testDeleteOne()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testDeleteOne" is-config="true" duration-ms="0" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteOne -->
        <test-method status="SKIP" signature="testInsert()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testInsert" is-config="true" duration-ms="0" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsert -->
        <test-method status="SKIP" signature="testUpdateOne()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testUpdateOne" is-config="true" duration-ms="0" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateOne -->
        <test-method status="SKIP" signature="testUpdateWhere()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testUpdateWhere" is-config="true" duration-ms="0" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateWhere -->
        <test-method status="SKIP" signature="testCount()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testCount" duration-ms="0" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <exception class="org.springframework.beans.factory.CannotLoadBeanClassException">
            <message>
              <![CDATA[Cannot find class [whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory] for bean with name 'myBatisSessionFactory' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory] for bean with name 'myBatisSessionFactory' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1385)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:641)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1007)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:741)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at whayer.cloud.framework.db.test.HibernateDaoTest.testGetDao(HibernateDaoTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:401)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1432)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1377)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- org.springframework.beans.factory.CannotLoadBeanClassException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCount -->
        <test-method status="SKIP" signature="testGroup()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testGroup" duration-ms="0" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <exception class="org.springframework.beans.factory.CannotLoadBeanClassException">
            <message>
              <![CDATA[Cannot find class [whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory] for bean with name 'myBatisSessionFactory' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory] for bean with name 'myBatisSessionFactory' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1385)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:641)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1007)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:741)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at whayer.cloud.framework.db.test.HibernateDaoTest.testGetDao(HibernateDaoTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:401)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1432)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1377)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- org.springframework.beans.factory.CannotLoadBeanClassException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGroup -->
        <test-method status="SKIP" signature="testSelectList()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testSelectList" duration-ms="0" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <exception class="org.springframework.beans.factory.CannotLoadBeanClassException">
            <message>
              <![CDATA[Cannot find class [whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory] for bean with name 'myBatisSessionFactory' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory] for bean with name 'myBatisSessionFactory' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1385)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:641)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1007)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:741)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at whayer.cloud.framework.db.test.HibernateDaoTest.testGetDao(HibernateDaoTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:401)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1432)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1377)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- org.springframework.beans.factory.CannotLoadBeanClassException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSelectList -->
        <test-method status="SKIP" signature="testSelectOne()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testSelectOne" duration-ms="0" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <exception class="org.springframework.beans.factory.CannotLoadBeanClassException">
            <message>
              <![CDATA[Cannot find class [whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory] for bean with name 'myBatisSessionFactory' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory] for bean with name 'myBatisSessionFactory' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1385)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:641)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1007)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:741)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at whayer.cloud.framework.db.test.HibernateDaoTest.testGetDao(HibernateDaoTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ClassNotFoundException: whayer.cloud.framework.data.db.dao.datasource.MyBatisDbSessionFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:401)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1432)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1377)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- org.springframework.beans.factory.CannotLoadBeanClassException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSelectOne -->
        <test-method status="SKIP" signature="testDeleteWhere()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testDeleteWhere" is-config="true" duration-ms="0" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteWhere -->
        <test-method status="SKIP" signature="testCloseConnection()[pri:0, instance:whayer.cloud.framework.db.test.HibernateDaoTest@578ef2b6]" name="testCloseConnection" is-config="true" duration-ms="0" started-at="2017-08-04T15:34:04Z" finished-at="2017-08-04T15:34:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCloseConnection -->
      </class> <!-- whayer.cloud.framework.db.test.HibernateDaoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
